package com.goku.demo.model;

public class UserWithBLOBs extends User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.description_
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.leftmenu
     *
     * @mbg.generated
     */
    private String leftmenu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.description_
     *
     * @return the value of user_.description_
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.description_
     *
     * @param description the value for user_.description_
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.leftmenu
     *
     * @return the value of user_.leftmenu
     *
     * @mbg.generated
     */
    public String getLeftmenu() {
        return leftmenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.leftmenu
     *
     * @param leftmenu the value for user_.leftmenu
     *
     * @mbg.generated
     */
    public void setLeftmenu(String leftmenu) {
        this.leftmenu = leftmenu == null ? null : leftmenu.trim();
    }
}